let british = [
    { 'aeroplane' : 'airplane'},
    { 'aeroplanes' : 'airplanes'},
    { 'aluminium' : 'aluminum'},
    { 'amongst' : 'among' },
    { 'apologise' : 'apologize' },
    { 'apologises' : 'apologizes' },
    { 'behaviourism' : 'behaviorism'}, 
    { 'behaviourist' : 'behaviorist'}, 
    { 'behaviourists' : 'behaviorists'}, 
    { 'behavioural' : 'behavioral'},
    { 'bin' : 'trash can'},
    { 'bins' : 'trash cans'},
    { 'car park' : 'parking lot' },
    { 'car parks' : 'parking lots' },
    { 'cheque' : 'check' },
    { 'cheques' : 'checks' },
    { 'colour' : 'color' },
    { 'colours' : 'colors' },
    { 'grey' : 'gray' },
    { 'favourite' : 'favorite' },
    { 'high street' : 'main street' },
    { 'harbour' : 'harbor' },
    { 'harbours' : 'harbors' },
    { 'holiday' : 'vocation' },
    { 'holidays' : 'vocations' },
    { 'humour' : 'humor' },
    { 'neighbour' : 'neighbor' },
    { 'neighbours' : 'neighbors' },
    { 'neighbourship' : 'neighborship' },
    { 'mobile phone' : 'cell phone' },
    { 'mobile phones' : 'cell phones' },
    { 'motorway' : 'highway' },
    { 'motorways' : 'highways' },
    { 'moustache' : 'mustache' },
    { 'queue' : 'line'},
    { 'queues' : 'lines'},
    { 'learnt' : 'learned' },
    { 'odour' : 'odor' },
    { 'petrol' : 'gas' },
    { 'programme' : 'program' },
    { 'programmes' : 'programs' },
    { 'postal code' : 'zip code' },
    { 'postal codes' : 'zip codes' },
    { 'rubbish' : 'garbage' },
    { 'rumour' : 'rumor' },
    { 'rumours' : 'rumors' },
    { 'speciality' : 'specialty' },
    { 'sweets' : 'candy' },
    { 'takeaway' : 'takeout'},
    { 'torch' : 'flashlight'},
    { 'torches' : 'flashlights'},
    { 'theatre' : 'theater'},
    { 'theatres' : 'theaters'},
].map(w => Object.keys(w))

export default british.join('|')