let phrasalVerbs = [
    'aim at', 'aimed at', 'aims at',
    'ask for', 'asks for', 'asked for', 
    'ask out','asks out','asked out', 
    'back down', 'backed down','backs down', 
    'back off', 'backs off', 'backed off', 
    'back up', 'backs up', 'backed up', 
    'beat up', 'beats up', 'beaten up', 
    'beef up', 'beefs up', 'beefed up', 
    'bite off', 'bites off', 'bit off', 
    'blow away', 'blows away', 'blew away', 
    'blow off', 'blows off', 'blew off', 
    'blow out', 'blows out', 'blew out', 
    'blow up', 'blows up', 'blew up', 
    'boil down', 'boils down', 'boiled down', 
    'break down', 'breaks down', 'broke down', 
    'break in', 'breaks in', 'broke in', 
    'break off', 'breaks off', 'broke off', 
    'break out', 'breaks out', 'broke out', 
    'break through', 'breaks through', 'broke through', 
    'break up', 'breaks up', 'broke up', 
    'bring about', 'brings about', 'brought about', 
    'bring over', 'brings over', 'brought over', 
    'bring out', 'brings out', 'brought out', 
    'bring up', 'brings up', 'brought up', 
    'brush off', 'brushes off', 'brushed off', 
    'brush up', 'brushes up', 'brushed up', 
    'build in', 'builds in', 'built in', 
    'build into', 'builds into', 'built into', 
    'bump into', 'bumps into', 'bumped into', 
    'burn down', 'burns down', 'burnt down', 
    'burn out', 'burns out', 'burnt out', 
    'burn up', 'burns up', 'burnt up', 
    'burst out', 'bursts out', 'burst out', 
    'butt in', 'butts in', 'butt in',
    'call back', 'calls back', 'called back', 
    'call in', 'calls in', 'called in', 
    'call off', 'calls off', 'called off', 
    'call up', 'calls up', 'called up',
    'calm down', 'calms down', 'calmed down',
    'care for', 'cares for', 'cared for', 
    'carry away', 'carries away', 'carried away',
    'carry on', 'carries on', 'carried on', 
    'carry out', 'carries out', 'carried out', 
    'catch on', 'caught on', 'caught on', 
    'catch up', 'caught up', 'caught up', 
    'cheat on', 'cheats on', 'cheated on',
    'check in', 'checks in', 'checked in',
    'check out', 'checks out', 'checked out',
    'chicken out', 'chickens out', 'chickened out',
    'chop up', 'chops up', 'chopped up',
    'clean out', 'cleans out', 'cleaned out',
    'clear out', 'clears out', 'cleared out', 
    'clear up', 'clears up', 'cleared up', 
    'clog up', 'clogs up', 'clogged up',
    'close down', 'closes down', 'closed down',
    'close off', 'closes off', 'closed off',
    'come about', 'comes about', 'came about', 
    'come across', 'comes across', 'came across', 
    'come apart', 'comes apart', 'came apart', 
    'come back', 'comes back', 'came back', 
    'come down', 'comes down', 'came down', 
    'come from', 'comes from', 'came from', 
    'come off', 'comes off', 'came off', 
    'come on', 'comes on', 'came on', 
    'come out', 'comes out', 'came out', 
    'come over', 'comes over', 'came over', 
    'come through', 'comes through', 'came through', 
    'come together', 'comes together', 'came together', 
    'come up', 'comes up', 'came up', 
    'come in', 'comes in', 'came in',
    'con into', 'cones into', 'conned into', 
    'con out', 'cones out', 'conned out',
    'cool off', 'cools off', 'cooled off',
    'count on', 'counts on', 'counted on', 
    'count up', 'counts up', 'counted up', 
    'cover up', 'covers up', 'covered up', 
    'crack down', 'cracks down', 'cracked down',
    'cross off', 'crosses off', 'crossed off',
    'cut back', 'cuts back', 
    'cut down', 'cuts down', 
    'cut off', 'cuts off', 
    'cut out', 'cuts out', 
    'cut up', 'cuts up', 
    'deal with', 'deals with', 'dealt with', 
    'do away', 'does away', 'done away', 'did away',
    'do over', 'does over', 'done over', 'did over',
    'do with', 'does with', 'done with', 'did with',
    'do without', 'does without', 'done without', 'did without',
    'doze off', 'dozes off', 'dozed off', 
    'dress up', 'dresses up', 'dressed up', 
    'drop in', 'drops in', 'dropped in', 
    'drop out', 'drops out', 'dropped out', 
    'drop off', 'drops off', 'dropped off', 
    'dry off', 'dries off', 'dried off', 
    'dry out', 'dries out', 'dried out', 
    'dry up', 'dries up', 'dried up', 
    'eat up', 'eats up', 'eaten up',
    'empty out', 'empties out', 'emptied out',
    'end up', 'ends up', 'ended up',
    'fall apart', 'falls apart', 'fell apart', 'fallen apart',
    'fall behind', 'falls behind', 'fell behind', 'fallen behind',
    'fall down', 'falls down', 'fell down', 'fallen down',
    'fall for', 'falls for', 'fell for', 'fallen for',
    'fall off', 'falls off', 'fell off', 'fallen off',
    'fall out', 'falls out', 'fell out', 'fallen out',
    'fall over', 'falls over', 'fell over', 'fallen over',
    'fall through', 'falls through', 'fell through', 'fallen through',
    'feel up', 'feels up', 'felt up',
    'fight back', 'fights back', 'fought back',
    'figure out', 'figures out', 'figured out', 
    'fill in', 'fills in', 'filled in',
    'fill out', 'fills out', 'filled out',
    'fill up', 'fills up', 'filled up',
    'find out', 'finds out', 'found out', 
    'fix up', 'fixes up', 'fixed up', 
    'flip out', 'flips out', 'flipped out', 
    'float around', 'floats around', 'floated around', 
    'follow up', 'follows up', 'followed up', 
    'fool around', 'fools around', 'fooled around', 
    'freak out', 'freaks out', 'freaked out', 
    'get ahead', 'gets ahead', 'got ahead', 
    'get along', 'gets along', 'got along', 
    'get around', 'gets around', 'got around', 
    'get away', 'gets away', 'got away',
    'get behind', 'gets behind', 'got behind',
    'get by', 'gets by', 'got by',
    'get down', 'gets down', 'got down',   
    'get in', 'gets in', 'got in',   
    'get off', 'gets off', 'got off',   
    'get on', 'gets on', 'got on',   
    'get out', 'gets out', 'got out',   
    'get over', 'gets over', 'got over',   
    'get through', 'gets over', 'got through',   
    'get to', 'gets to', 'got to',   
    'get together', 'gets together', 'got together',   
    'get up', 'gets up', 'got up',   
    'give away',  'gives away',  'gave away', 'given away' ,
    'give in',  'gives in',  'gave in', 'given in' ,
    'give up',  'gives up',  'gave up', 'given up' ,
    'go about', 'goes about', 'went about', 'gone about',
    'go after', 'goes after', 'went after', 'gone after',
    'go ahead', 'goes ahead', 'went ahead', 'gone ahead',
    'go along', 'goes along', 'went along', 'gone along',
    'go around', 'goes around', 'went around', 'gone around',
    'go away', 'goes away', 'went away', 'gone away',
    'go back', 'goes back', 'went back', 'gone back',
    'go beyond', 'goes beyond', 'went beyond', 'gone beyond',
    'go by', 'goes by', 'went by', 'gone by',
    'go down', 'goes down', 'went down', 'gone down',
    'go for', 'goes for', 'went for', 'gone for',
    'go in', 'goes in', 'went in', 'gone in',
    'go into', 'goes into', 'went into', 'gone into',
    'go off', 'goes off', 'went off', 'gone off',
    'go on', 'goes on', 'went on', 'gone on',
    'go out', 'goes out', 'went out', 'gone out',
    'go over', 'goes over', 'went over', 'gone over',
    'go through', 'goes through', 'went through', 'gone through',
    'go up', 'goes up', 'went up', 'gone up',
    'go with', 'goes with', 'went with', 'gone with',
    'goof around', 'goofs around', 'goofed around',
    'gross out', 'grosses out', 'grossed out', 
    'grow out',  'grows out',  'grew out',
    'grow up',  'grows up',  'grew up', 'grown up',
    'hand back', 'hands back', 'handed back', 
    'hand out', 'hands out', 'handed out', 
    'hand in', 'hands in', 'handed in', 
    'hand over', 'hands over', 'handed over', 
    'hang around', 'hangs around', 'hanged around', 
    'hang on', 'hangs on', 'hanged on', 
    'hang out', 'hangs out', 'hanged out', 
    'hang up', 'hangs up', 'hanged up', 
    'head back', 'heads back', 'headed back', 
    'head for', 'heads for', 'headed for', 
    'head toward', 'heads toward', 'headed toward', 
    'hear about',  'hears about',  'heard about', 
    'hear of', 'hears of', 'heard of', 
    'heat up', 'heats up', 'heated up', 
    'help out',  'helps out',  'helped out', 
    'hit on', 'hits on', 
    'hold against', 'holds against', 'held against', 
    'hold off', 'holds off', 'held off', 
    'hold on', 'holds on', 'held on', 
    'hold out', 'holds out', 'held out', 
    'hold up', 'holds up', 'held up',
    'hook up', 'hooks up', 'hooked up',
    'hurry up', 'hurries up', 'hurried up', 
    'keep at', 'keeps at', 'kept at',
    'keep away', 'keeps away', 'kept away',
    'keep down', 'keeps down', 'kept down',
    'keep from', 'keeps from', 'kept from',
    'keep off', 'keeps off', 'kept off',
    'keep on', 'keeps on', 'kept on',
    'keep to', 'keeps on', 'kept to',
    'keep up', 'keeps up', 'kept up',
    'kick back', 'kicks back', 'kicked back', 
    'kick out', 'kicks out', 'kicked out', 
    'knock off', 'knocks off', 'knocked off',
    'knock out', 'knocks out', 'knocked out',
    'knock over', 'knocks over', 'knocked over',
    'know about', 'knows about', 'knew about', 
    'lay down', 'lays down', 'laid down', 
    'lay off', 'lays off', 'laid off', 
    'lead up', 'leads up', 'led up',
    'leave behind', 'leaves behind', 'left behind',
    'leave off', 'leaves off', 'left off',
    'leave out', 'leaves out', 'left out',
    'leave over', 'leaves over', 'left over',
    'let down', 'lets down',
    'let in', 'lets in',
    'let off', 'lets off',
    'let on', 'lets on',
    'let out', 'lets out',
    'let up', 'lets up',
    'lie around', 'lies around', 'lay around', 'lied around',
     'lift up', 'lifts up', 'lifted up', 'lit up',
    'line up', 'lines up', 'lined up', 
    'live with', 'lives with', 'lived with',
    'lock in', 'locks in', 'locked in',
    'lock out', 'locks out', 'locked out', 
    'lock up', 'locks up', 'locked up',
    'look around', 'looks around', 'looked around',
    'look at', 'looks at', 'looked at',
    'look down', 'looks down', 'looked down',
    'look for', 'looks for', 'looked for',
    'look forward', 'looks forward', 'looked forward',
    'look into', 'looks into', 'looked into',
    'look out', 'looks out', 'looked out',
    'look over', 'looks over', 'looked over',
    'look out', 'looks out', 'looked out',
    'luck out', 'lucks out', 'lucked out',
    'make for', 'makes for',
    'make of', 'makes of',
    'make up', 'makes up', 'made up',
    'mess up', 'messes up', 'messed up', 
    'mix up', 'mixes up', 'mixed up',
    'monkey around', 'monkeys around', 'monkeyed around',
    'move in', 'moves in', 'moved in',
    'move out', 'moves out', 'moved out', 
    'narrow down', 'narrows down', 'narrowed down',
    'pay back', 'pays back', 'payed back',
    'pay for', 'pays for', 'payed for',
    'pay off', 'pays off', 'payed off',
    'pay up', 'pays up', 'payed up',
    'pick on', 'picks on', 'picked on', 
    'pick out', 'picks out', 'picked out',
    'pick up', 'picks up', 'picked up', 
    'pile up', 'piles up', 'piled up',
    'piss off', 'pisses off', 'pissed off', 
    'plan ahead', 'plans ahead', 'planed ahead',
    'plan for', 'plans for', 'planed for', 
    'plan on', 'plans on', 'planed on',
    'plug in', 'plugs in', 'plugged in', 
    'plug into', 'plugs into', 'plugged into', 
    'plug out', 'plugs out', 'plugged out', 
    'point out', 'points out', 'pointed out',
    'point to', 'points tp', 'pointed to',
    'print out', 'prints out', 'printed out',
    'pull off', 'pulls off', 'pulled off',
    'pull up', 'pulls up', 'pulled up',
    'pull back', 'pulls back', 'pulled back',
    'put down', 'puts down',
    'put in', 'puts in',
    'put off', 'puts off',
    'put out', 'puts out',
    'put past', 'puts past',
    'put to', 'puts to',
    'put together', 'puts together',
    'put up', 'puts up',
    'ring up', 'rings up', 'ringed up',
    'rip off', 'rips off', 'ripped off',
    'rip up', 'rips up', 'ripped up',
    'rule out', 'rules out', 'ruled out',
    'run across', 'runs across','ran across',
    'run down', 'runs down','ran down',
    'run over', 'runs over','ran over',
    'run up', 'runs up','ran up',
    'screw on', 'screws on', 'screwed on',
    'screw out', 'screws out', 'screwed out',
    'screw up', 'screws up', 'screwed up',
    'see about', 'sees about', 'seen about', 'saw about',
    'sell out', 'sells out', 'sold out', 
    'set up', 'sets up',
    'settle down', 'settles down', 'settled down', 
    'settle for', 'settles for', 'settled for', 
    'shake up', 'shakes up', 'shaken up', 
    'show off', 'shows off', 'showed off',
    'shun away', 'shuns away', 'shunned away',
    'shut off', 'shuts off', 
    'shut up', 'shuts up', 
    'sign in', 'signs in', 'signed in',
    'sign out', 'signs out', 'signed out',
    'sit down', 'sits down', 'sat down', 
    'slow down', 'slows down', 'slowed down',
    'sneak in', 'sneaks in', 'sneaked in',
    'sneak out', 'sneaks out', 'sneaked out', 
    'sort out', 'sorts out', 'sorted out', 
    'space out', 'spaces out', 'spaced out',
    'speed up', 'speeds up', 'speeded up',
    'stand around', 'stands around', 'stood around',
    'stand for', 'stands for', 'stood for', 
    'stand up', 'stands up', 'stood up',
    'start off', 'starts off', 'started off', 
    'start out', 'starts out', 'started out', 
    'start up', 'starts up', 'started up', 
    'stay off', 'stays off', 'stayed off', 
    'stay out', 'stays out', 'stayed out', 
    'stay up', 'stays up', 'stayed up', 
    'step on', 'steps on', 'stepped on',
    'step back', 'steps back', 'stepped back',
    'stick around', 'sticks around', 'sticked around', 
    'stick out', 'sticks out', 'sticked out', 
    'stick to', 'sticks to', 'sticked to', 
    'stick up', 'sticks up', 'sticked up', 
    'stick with', 'sticks with', 'sticked with', 
    'stop off', 'stops off', 'stopped off', 
    'stop over', 'stops over', 'stopped over', 
    'stop out', 'stops out', 'stopped out', 
    'straighten out', 'straightens out', 'straightened out',
    'stress out', 'stresses out', 'stressed out', 
    'switch off', 'switches off', 'switched off',
    'switch on', 'switches on', 'switched on',
    'take away', 'takes away', 'took away', 'taken away',
    'take part', 'takes part', 'took part', 'taken part',
    'take back', 'takes back', 'took back', 'taken back',
    'take in', 'takes in', 'took in', 'taken in',
    'take out', 'takes out', 'took out', 'taken out',
    'take up', 'takes up', 'took up', 'taken up',
    'talk down', 'talks down', 'talked down',
    'talk into', 'talks into', 'talked into',
    'talk out', 'talks out', 'talked out',
    'tear down', 'tears down', 'teared down', 
    'tear off', 'tears off', 'teared off', 
    'tell apart', 'tells apart', 'told apart',
    'tell on', 'tells on', 'told on', 
    'think about', 'thinks about', 'thought about',
    'think over', 'thinks over', 'thought over',
    'think ahead', 'thinks ahead', 'thought ahead',
    'think up', 'thinks up', 'thought up',
    'throw away', 'throws away', 'threw away', 
    'throw out', 'throws out', 'threw out', 
    'throw up', 'throws up', 'threw up', 
    'track down', 'tracks down', 'tracked down',
    'trade in', 'trades in', 'traded in',
    'trick into', 'tricks into', 'tricked into',
    'try on', 'tries on', 'tried on', 
    'try out', 'tries out', 'tried out', 
    'turn around', 'turns around', 'turned around',
    'turn down', 'turns down', 'turned down',
    'turn in', 'turns in', 'turned in',
    'turn into', 'turns into', 'turned into',
    'turn off', 'turns off', 'turned off',
    'turn on', 'turns on', 'turned on',
    'turn out', 'turns out', 'turned out',
    'turn over', 'turns over', 'turned over',
    'turn up', 'turns up', 'turned up',
    'use up', 'uses up', 'used up', 
    'wake up', 'wakes up', 'waked up', 
    'wash off', 'washes off', 'washed off',
    'wash up', 'washes up', 'washed up',
    'watch out', 'watches out', 'watched out',
    'wear down', 'wears down', 'wore down', 
    'wear off', 'wears off', 'wore off', 
    'wear out', 'wears out', 'wore out', 
    'wind up', 'winds up', 'winded up',
    'wipe off', 'wipes off', 'wiped off',
    'wipe out', 'wipes out', 'wiped out',
    'wipe up', 'wipes up', 'wiped up',
    'work in', 'works in', 'worked in',
    'work out', 'works out', 'worked out',
    'work up', 'works up', 'worked up',
    'wrap up', 'wraps up', 'wrapped up',
    'zip up', 'zips up', 'zipped up']



export default phrasalVerbs;