let phrasalVerbs = [
    'aim at', 'aimed at', 'aims at','aiming at',
    'ask for', 'asks for', 'asked for', 'asking for',
    'ask out','asks out','asked out', 'asking out',
    'back down', 'backed down','backs down', 'back down',
    'back off', 'backs off', 'backed off', 'backing off',
    'back up', 'backs up', 'backed up', 'backing up',
    'beat up', 'beats up', 'beaten up', 'beating up',
    'beef up', 'beefs up', 'beefed up', 'beefing up',
    'bite off', 'bites off', 'bit off', 'biting off',
    'blow away', 'blows away', 'blew away', 'blowing away',
    'blow off', 'blows off', 'blew off', 'blowing off',
    'blow out', 'blows out', 'blew out', 'blowing out',
    'blow up', 'blows up', 'blew up', 'blowing up',
    'boil down', 'boils down', 'boiled down', 'boiling down',
    'break down', 'breaks down', 'broke down', 'breaking down',
    'break in', 'breaks in', 'broke in', 'breaking in',
    'break off', 'breaks off', 'broke off', 'breaking off',
    'break out', 'breaks out', 'broke out', 'breaking out',
    'break through', 'breaks through', 'broke through', 'breaking through',
    'break up', 'breaks up', 'broke up', 'breaking up',
    'bring about', 'brings about', 'brought about', 'bringing about',
    'bring over', 'brings over', 'brought over', 'bringing over',
    'bring out', 'brings out', 'brought out', 'bringing out',
    'bring up', 'brings up', 'brought up', 'bringing up',
    'brush off', 'brushes off', 'brushed off', 'brushing off',
    'brush up', 'brushes up', 'brushed up', 'brushing up',
    'build in', 'builds in', 'built in', 'building in',
    'build into', 'builds into', 'built into', 'building into',
    'bump into', 'bumps into', 'bumped into', 'bumping into',
    'burn down', 'burns down', 'burnt down', 'burning down',
    'burn out', 'burns out', 'burnt out', 'burning out',
    'burn up', 'burns up', 'burnt up', 'burning up',
    'burst out', 'bursts out', 'burst out', 'bursting out',
    'butt in', 'butts in', 'butt in','butting in',
    'call back', 'calls back', 'called back', 'calling back',
    'call in', 'calls in', 'called in', 'calling in',
    'call off', 'calls off', 'called off', 'calling off',
    'call up', 'calls up', 'called up','calling up',
    'calm down', 'calms down', 'calmed down','calming down',
    'care for', 'cares for', 'cared for', 'caring for',
    'carry away', 'carries away', 'carried away','carrying away',
    'carry on', 'carries on', 'carried on', 'carrying on',
    'carry out', 'carries out', 'carried out', 'carrying on',
    'catch on', 'caught on', 'caught on', 'catching on',
    'catch up', 'caught up', 'caught up', 'catching up',
    'cheat on', 'cheats on', 'cheated on', 'catching on',
    'check in', 'checks in', 'checked in', 'checking in',
    'check out', 'checks out', 'checked out', 'checking out',
    'chicken out', 'chickens out', 'chickened out','chickening out',
    'chop up', 'chops up', 'chopped up', 'chopping up',
    'clean out', 'cleans out', 'cleaned out','cleaning out',
    'clear out', 'clears out', 'cleared out', 'clearing out',
    'clear up', 'clears up', 'cleared up', 'clearing up',
    'clog up', 'clogs up', 'clogged up', 'clogging up',
    'close down', 'closes down', 'closed down','closing down',
    'close off', 'closes off', 'closed off', 'closing off',
    'come about', 'comes about', 'came about', 'coming about',
    'come across', 'comes across', 'came across', 'coming across',
    'come apart', 'comes apart', 'came apart', 'coming apart',
    'come back', 'comes back', 'came back', 'coming back',
    'come down', 'comes down', 'came down', 'coming down',
    'come from', 'comes from', 'came from', 'coming from',
    'come off', 'comes off', 'came off', 'coming off',
    'come on', 'comes on', 'came on', 'coming on',
    'come out', 'comes out', 'came out', 'coming out',
    'come over', 'comes over', 'came over', 'coming over',
    'come through', 'comes through', 'came through', 'coming through',
    'come together', 'comes together', 'came together', 'coming together',
    'come up', 'comes up', 'came up', 'coming up',
    'come in', 'comes in', 'came in','coming in',
    'con into', 'cones into', 'conned into', 'conning into',
    'con out', 'cones out', 'conned out','conning out',
    'cool off', 'cools off', 'cooled off','cooling off',
    'count on', 'counts on', 'counted on', 'counting on',
    'count up', 'counts up', 'counted up', 'counting up',
    'cover up', 'covers up', 'covered up', 'covering up',
    'crack down', 'cracks down', 'cracked down', 'cracking down',
    'cross off', 'crosses off', 'crossed off','crossing off',
    'cut back', 'cuts back', 'cutting back',
    'cut down', 'cuts down', 'cutting down',
    'cut off', 'cuts off', 'cutting off',
    'cut out', 'cuts out', 'cutting out',
    'cut up', 'cuts up', 'cutting up',
    'deal with', 'deals with', 'dealt with','dealing with', 
    'do away', 'does away', 'done away', 'did away','doing away',
    'do over', 'does over', 'done over', 'did over','doing over',
    'do with', 'does with', 'done with', 'did with','doing with',
    'do without', 'does without', 'done without', 'did without', 'doing without',
    'doze off', 'dozes off', 'dozed off', 'dozing off',
    'dress up', 'dresses up', 'dressed up', 'dressing up',
    'drop in', 'drops in', 'dropped in', 'dropping in',
    'drop out', 'drops out', 'dropped out', 'dropping out',
    'drop off', 'drops off', 'dropped off', 'dropping off',
    'dry off', 'dries off', 'dried off', 'drying off',
    'dry out', 'dries out', 'dried out', 'drying out',
    'dry up', 'dries up', 'dried up', 'drying up',
    'eat up', 'eats up', 'eaten up', 'eating up',
    'empty out', 'empties out', 'emptied out','emptying out',
    'end up', 'ends up', 'ended up', 'ending up',
    'fall apart', 'falls apart', 'fell apart', 'fallen apart', 'falling apart',
    'fall behind', 'falls behind', 'fell behind', 'fallen behind','falling behind',
    'fall down', 'falls down', 'fell down', 'fallen down','falling down',
    'fall for', 'falls for', 'fell for', 'fallen for', 'falling for',
    'fall off', 'falls off', 'fell off', 'fallen off', 'falling off',
    'fall out', 'falls out', 'fell out', 'fallen out', 'falling out',
    'fall over', 'falls over', 'fell over', 'fallen over','falling over',
    'fall through', 'falls through', 'fell through', 'fallen through','falling through',
    'feel up', 'feels up', 'felt up','feeling up',
    'fight back', 'fights back', 'fought back','fighting back',
    'figure out', 'figures out', 'figured out', 'figuring out',
    'fill in', 'fills in', 'filled in','filling in',
    'fill out', 'fills out', 'filled out','filling out',
    'fill up', 'fills up', 'filled up','filling up',
    'find out', 'finds out', 'found out', 'finding out',
    'fix up', 'fixes up', 'fixed up', 'fixing up',
    'flip out', 'flips out', 'flipped out', 'flipping out',
    'float around', 'floats around', 'floated around', 'floating around',
    'follow up', 'follows up', 'followed up', 'following up',
    'fool around', 'fools around', 'fooled around', 'fooling around',
    'freak out', 'freaks out', 'freaked out', 'freaking out',
    'get ahead', 'gets ahead', 'got ahead', 'getting ahead',
    'get along', 'gets along', 'got along', 'getting along',
    'get around', 'gets around', 'got around', 'getting around',
    'get away', 'gets away', 'got away','getting away',
    'get behind', 'gets behind', 'got behind','getting behind',
    'get by', 'gets by', 'got by','getting by',
    'get down', 'gets down', 'got down', 'getting down',  
    'get in', 'gets in', 'got in', 'getting in',  
    'get off', 'gets off', 'got off','getting off',   
    'get on', 'gets on', 'got on','getting on',   
    'get out', 'gets out', 'got out','getting out',   
    'get over', 'gets over', 'got over', 'getting over',  
    'get through', 'gets over', 'got through', 'getting through',  
    'get to', 'gets to', 'got to',   'getting to',
    'get together', 'gets together', 'got together', 'getting together', 
    'get up', 'gets up', 'got up', 'getting up',  
    'give away',  'gives away',  'gave away', 'given away' ,'giving away',
    'give in',  'gives in',  'gave in', 'given in' ,'giving in',
    'give up',  'gives up',  'gave up', 'given up' ,'giving up',
    'go about', 'goes about', 'went about', 'gone about', 'going about',
    'go after', 'goes after', 'went after', 'gone after', 'going after',
    'go ahead', 'goes ahead', 'went ahead', 'gone ahead', 'going ahead',
    'go along', 'goes along', 'went along', 'gone along', 'going along',
    'go around', 'goes around', 'went around', 'gone around', 'going around',
    'go away', 'goes away', 'went away', 'gone away','going away',
    'go back', 'goes back', 'went back', 'gone back', 'going back',
    'go beyond', 'goes beyond', 'went beyond', 'gone beyond', 'going beyond',
    'go by', 'goes by', 'went by', 'gone by', 'going by',
    'go down', 'goes down', 'went down', 'gone down', 'going down',
    'go for', 'goes for', 'went for', 'gone for', 'going for',
    'go in', 'goes in', 'went in', 'gone in', 'going in',
    'go into', 'goes into', 'went into', 'gone into', 'going into',
    'go off', 'goes off', 'went off', 'gone off', 'going off',
    'go on', 'goes on', 'went on', 'gone on', 'going on',
    'go out', 'goes out', 'went out', 'gone out', 'going out',
    'go over', 'goes over', 'went over', 'gone over', 'going over',
    'go through', 'goes through', 'went through', 'gone through', 'going through',
    'go up', 'goes up', 'went up', 'gone up', 'going up',
    'go with', 'goes with', 'went with', 'gone with', 'going with',
    'goof around', 'goofs around', 'goofed around','goofing around',
    'gross out', 'grosses out', 'grossed out', 'grossing out',
    'grow out',  'grows out',  'grew out','growing out',
    'grow up',  'grows up',  'grew up', 'grown up','growing up',
    'hand back', 'hands back', 'handed back', 'handing back',
    'hand out', 'hands out', 'handed out', 'handing out',
    'hand in', 'hands in', 'handed in', 'handing in',
    'hand over', 'hands over', 'handed over', 'handing over',
    'hang around', 'hangs around', 'hanged around', 'hanging around',
    'hang on', 'hangs on', 'hanged on', 'hanging on',
    'hang out', 'hangs out', 'hanged out', 'hanging out',
    'hang up', 'hangs up', 'hanged up', 'hanging up',
    'head back', 'heads back', 'headed back', 'heading back',
    'head for', 'heads for', 'headed for', 'heading for',
    'head toward', 'heads toward', 'headed toward', 'heading toward',
    'hear about',  'hears about',  'heard about', 'heading about',
    'hear of', 'hears of', 'heard of', 'heading of',
    'heat up', 'heats up', 'heated up', 'heating up',
    'help out',  'helps out',  'helped out', 'helping out',
    'hit on', 'hits on', 'hitting on',
    'hold against', 'holds against', 'held against', 'holding against',
    'hold off', 'holds off', 'held off', 'holding off',
    'hold on', 'holds on', 'held on', 'holding on',
    'hold out', 'holds out', 'held out', 'holding out',
    'hold up', 'holds up', 'held up','holding up',
    'hook up', 'hooks up', 'hooked up','hooking up',
    'hurry up', 'hurries up', 'hurried up', 'hurrying up',
    'keep at', 'keeps at', 'kept at','keeping at',
    'keep away', 'keeps away', 'kept away','keeping away',
    'keep down', 'keeps down', 'kept down','keeping down',
    'keep from', 'keeps from', 'kept from','keeping from',
    'keep off', 'keeps off', 'kept off','keeping off',
    'keep on', 'keeps on', 'kept on','keeping on',
    'keep to', 'keeps on', 'kept to','keeping to',
    'keep up', 'keeps up', 'kept up','keeping up',
    'kick back', 'kicks back', 'kicked back', 'kicking back',
    'kick out', 'kicks out', 'kicked out', 'kicking out',
    'knock off', 'knocks off', 'knocked off','knocking off',
    'knock out', 'knocks out', 'knocked out','knocking out',
    'knock over', 'knocks over', 'knocked over','knocking over',
    'know about', 'knows about', 'knew about', 'knowing about',
    'lay down', 'lays down', 'laid down', 'laying down',
    'lay off', 'lays off', 'laid off', 'laying off',
    'lead up', 'leads up', 'led up','leading up',
    'leave behind', 'leaves behind', 'left behind','leaving behind',
    'leave off', 'leaves off', 'left off','leaving off',
    'leave out', 'leaves out', 'left out','leaving out',
    'leave over', 'leaves over', 'left over','leaving over',
    'let down', 'lets down','letting down',
    'let in', 'lets in','letting in',
    'let off', 'lets off','letting off',
    'let on', 'lets on', 'letting on',
    'let out', 'lets out', 'letting out',
    'let up', 'lets up','letting up',
    'lie around', 'lies around', 'lay around', 'lied around', 'lying around',
     'lift up', 'lifts up', 'lifted up', 'lit up','lifting up',
    'line up', 'lines up', 'lined up', 'lining up',
    'live with', 'lives with', 'lived with','living with',
    'lock in', 'locks in', 'locked in','locking in',
    'lock out', 'locks out', 'locked out', 'locking out',
    'lock up', 'locks up', 'locked up','locking up',
    'look around', 'looks around', 'looked around','looking around',
    'look at', 'looks at', 'looked at','looking at',
    'look down', 'looks down', 'looked down','looking down',
    'look for', 'looks for', 'looked for','looking for',
    'look forward', 'looks forward', 'looked forward','looking forward',
    'look into', 'looks into', 'looked into','looking into',
    'look out', 'looks out', 'looked out','looking out',
    'look over', 'looks over', 'looked over','looking over',
    'look out', 'looks out', 'looked out','looking out',
    'luck out', 'lucks out', 'lucked out','lucking out',
    'make for', 'makes for','making for',
    'make of', 'makes of','making of',
    'make up', 'makes up', 'made up','making up',
    'mess up', 'messes up', 'messed up', 'messing up',
    'mess around', 'messes around', 'messed around', 'messing around',
    'mix up', 'mixes up', 'mixed up','mixing up',
    'monkey around', 'monkeys around', 'monkeyed around','monkeying around',
    'move in', 'moves in', 'moved in','moving in',
    'move out', 'moves out', 'moved out', 'moving out',
    'narrow down', 'narrows down', 'narrowed down','narrowing down',
    'pay back', 'pays back', 'payed back','paying back',
    'pay for', 'pays for', 'payed for','paying for',
    'pay off', 'pays off', 'payed off','paying off',
    'pay up', 'pays up', 'payed up','paying up',
    'pick on', 'picks on', 'picked on', 'picking on',
    'pick out', 'picks out', 'picked out','picking out',
    'pick up', 'picks up', 'picked up', 'picking up',
    'pile up', 'piles up', 'piled up','pilling up',
    'piss off', 'pisses off', 'pissed off', 'pissing off',
    'plan ahead', 'plans ahead', 'planed ahead','planning ahead',
    'plan for', 'plans for', 'planed for', 'planning for',
    'plan on', 'plans on', 'planed on','planning on',
    'plug in', 'plugs in', 'plugged in', 'plugging in',
    'plug into', 'plugs into', 'plugged into', 'plugging into',
    'plug out', 'plugs out', 'plugged out', 'plugging out',
    'point out', 'points out', 'pointed out','pointing out',
    'point to', 'points tp', 'pointed to','pointing to',
    'print out', 'prints out', 'printed out','printing out',
    'pull off', 'pulls off', 'pulled off','pulling off',
    'pull up', 'pulls up', 'pulled up','pulling up',
    'pull back', 'pulls back', 'pulled back','pulling back',
    'put down', 'puts down','putting down',
    'put in', 'puts in','putting in',
    'put off', 'puts off','putting off',
    'put out', 'puts out','putting out',
    'put past', 'puts past','putting past',
    'put to', 'puts to','putting to',
    'put together', 'puts together',
    'put up', 'puts up','putting up',
    'ring up', 'rings up', 'ringed up','ringing up',
    'rip off', 'rips off', 'ripped off','ripping off',
    'rip up', 'rips up', 'ripped up','ripping up',
    'rule out', 'rules out', 'ruled out','ruling out',
    'run across', 'runs across','ran across','running across',
    'run down', 'runs down','ran down','running down',
    'run over', 'runs over','ran over','running over',
    'run up', 'runs up','ran up','running up',
    'screw on', 'screws on', 'screwed on','screwing on',
    'screw out', 'screws out', 'screwed out','screwing out',
    'screw up', 'screws up', 'screwed up','screwing up',
    'see about', 'sees about', 'seen about', 'saw about', 'seeing about',
    'sell out', 'sells out', 'sold out', 'selling out',
    'set up', 'sets up','setting up',
    'settle down', 'settles down', 'settled down','settling down', 
    'settle for', 'settles for', 'settled for', 'setting for',
    'shake up', 'shakes up', 'shaken up', 'shacking up',
    'show off', 'shows off', 'showed off','showing off',
    'shun away', 'shuns away', 'shunned away','shunning away',
    'shut off', 'shuts off', 'shutting off',
    'shut up', 'shuts up', 'shutting up',
    'sign in', 'signs in', 'signed in','signing in',
    'sign out', 'signs out', 'signed out','signing out',
    'sit down', 'sits down', 'sat down', 'sitting down',
    'slow down', 'slows down', 'slowed down','slowing down',
    'sneak in', 'sneaks in', 'sneaked in','sneaking in',
    'sneak out', 'sneaks out', 'sneaked out', 'sneaking out',
    'sort out', 'sorts out', 'sorted out', 'sorting out',
    'space out', 'spaces out', 'spaced out','spacing out',
    'speed up', 'speeds up', 'speeded up','speeding up',
    'stand around', 'stands around', 'stood around','standing around',
    'stand for', 'stands for', 'stood for', 'standing for',
    'stand up', 'stands up', 'stood up','standing up',
    'start off', 'starts off', 'started off', 'starting off',
    'start out', 'starts out', 'started out', 'starting out',
    'start up', 'starts up', 'started up', 'starting up',
    'stay off', 'stays off', 'stayed off', 'staying off',
    'stay out', 'stays out', 'stayed out', 'staying out',
    'stay up', 'stays up', 'stayed up', 'staying up',
    'step on', 'steps on', 'stepped on','stepping on',
    'step back', 'steps back', 'stepped back','stepping back',
    'stick around', 'sticks around', 'sticked around', 'sticking around',
    'stick out', 'sticks out', 'sticked out', 'sticking out',
    'stick to', 'sticks to', 'sticked to', 'sticking to',
    'stick up', 'sticks up', 'sticked up', 'sticking up',
    'stick with', 'sticks with', 'sticked with', 'sticking with',
    'stop off', 'stops off', 'stopped off', 'stopping off',
    'stop over', 'stops over', 'stopped over', 'stopping over',
    'stop out', 'stops out', 'stopped out', 'stopping out',
    'straighten out', 'straightens out', 'straightened out', 'straightening out',
    'stress out', 'stresses out', 'stressed out', 'stressing out',
    'switch off', 'switches off', 'switched off','switching off',
    'switch on', 'switches on', 'switched on','switching on',
    'take away', 'takes away', 'took away', 'taken away','taking away',
    'take part', 'takes part', 'took part', 'taken part','taking part',
    'take back', 'takes back', 'took back', 'taken back','taking back',
    'take in', 'takes in', 'took in', 'taken in','taking in',
    'take out', 'takes out', 'took out', 'taken out','taking out',
    'take up', 'takes up', 'took up', 'taken up','taking up',
    'talk down', 'talks down', 'talked down','talking down',
    'talk into', 'talks into', 'talked into','talking into',
    'talk out', 'talks out', 'talked out','talking out',
    'tear down', 'tears down', 'teared down', 'tearing down',
    'tear off', 'tears off', 'teared off', 'tearing off',
    'tear apart', 'tears apart', 'teared apart', 'tearing apart',
    'tell apart', 'tells apart', 'told apart','telling apart',
    'tell on', 'tells on', 'told on', 'telling on',
    'think about', 'thinks about', 'thought about','thinking about',
    'think over', 'thinks over', 'thought over','thinking over',
    'think ahead', 'thinks ahead', 'thought ahead','thinking ahead',
    'think up', 'thinks up', 'thought up','thinking up',
    'throw away', 'throws away', 'threw away', 'throwing away',
    'throw out', 'throws out', 'threw out', 'throwing out',
    'throw up', 'throws up', 'threw up', 'throwing up',
    'track down', 'tracks down', 'tracked down','tracking down',
    'trade in', 'trades in', 'traded in','trading in',
    'trick into', 'tricks into', 'tricked into','trucking into',
    'try on', 'tries on', 'tried on', 'trying on',
    'try out', 'tries out', 'tried out', 'trying out',
    'turn around', 'turns around', 'turned around','turing around',
    'turn down', 'turns down', 'turned down','turing down',
    'turn in', 'turns in', 'turned in','turning in',
    'turn into', 'turns into', 'turned into','turning into',
    'turn off', 'turns off', 'turned off','turning off',
    'turn on', 'turns on', 'turned on','turning on',
    'turn out', 'turns out', 'turned out','turning out',
    'turn over', 'turns over', 'turned over','turning over',
    'turn up', 'turns up', 'turned up','turning up',
    'use up', 'uses up', 'used up', 'using up',
    'wake up', 'wakes up', 'waked up', 'waking up',
    'wash off', 'washes off', 'washed off','washing off',
    'wash up', 'washes up', 'washed up','washing up',
    'watch out', 'watches out', 'watched out','watching out',
    'wear down', 'wears down', 'wore down','wearing down', 
    'wear off', 'wears off', 'wore off', 'wearing off',
    'wear out', 'wears out', 'wore out', 'wearing out',
    'wind up', 'winds up', 'winded up','winding up',
    'wipe off', 'wipes off', 'wiped off','wiping off',
    'wipe out', 'wipes out', 'wiped out','wiping out',
    'wipe up', 'wipes up', 'wiped up','wiping up',
    'work in', 'works in', 'worked in','working in',
    'work out', 'works out', 'worked out','working out',
    'work up', 'works up', 'worked up','working up',
    'wrap up', 'wraps up', 'wrapped up','wrapping up',
    'zip up', 'zips up', 'zipped up','zipping up'
]



export default phrasalVerbs;