let phrasalVerbs = ['aim at', 'ask for', 'ask out', 'back down', 'back off', 'back up', 'beat up', 'beef up', 'believe in', 'bite off', 'blow away', 'blow off', 'blow out', 'blow up', 'boil down', 'break down', 'break in', 'break off', 'break out', 'break through', 'break up', 'bring about', 'brought about', 'bring over','bring out','bring up', 'brush off', 'brush up', 'build in/into', 'bump into', 'burn down', 'burn out', 'burn up', 'burst out', 'butt in', 'call back', 'call in', 'call off', 'call up', 'calm down', 'care for', 'carry away', 'carry on', 'carry out','carried out', 'catch on', 'catch up', 'cheat on', 'check in', 'check out', 'chicken out', 'chop up', 'clean out', 'clear out', 'clear up', 'clog up', 'close down', 'close off', 'come about', 'come across', 'come apart', 'come back', 'come down', 'come down', 'come down', 'come in', 'come off', 'come on', 'come out', 'come over', 'come through', 'come up', 'come up', 'con into', 'con out', 'cool off', 'count on', 'count up', 'cover up', 'crack down', 'cross off', 'cut back', 'cut down', 'cut off', 'cut out', 'cut up', 'deal with', 'do away', 'do over', 'do with', 'do without', 'doze off', 'dress up', 'drop in', 'drop off', 'drop out', 'dry off', 'dry out', 'dry up', 'eat up', 'empty out', 'end up','ended up', 'fall apart', 'fall behind', 'fall down', 'fall for', 'fall off', 'fall out', 'fall over', 'fall through', 'feel up', 'fight back', 'figure out', 'fill in', 'fill out', 'fill up', 'find out', 'fix up', 'flip out', 'float around', 'follow up', 'fool around', 'freak out', 'get ahead', 'get along', 'get around', 'get away',
'get back', 'get back', 'get back', 'get behind', 'get by', 'get down', 'get in', 'get off', 'get off', 'get on', 'get out', 'get out', 'get over', 'get over', 'get through', 'get to', 'get together', 'get up', 'give away', 'give in', 'give out', 'give up', 'go about', 'go after', 'go ahead', 'go along', 'go around', 'go away', 'go back', 'go back', 'go beyond', 'go by', 'go down', 'go for', 'go in', 'go in', 'go in/into', 'go off', 'go on', 'go out', 'go over', 'go through', 'go up', 
'go with', 'goof around', 'gross out', 'grow out', 'grow up', 'hand back', 'hand in', 'hand out', 'hand over', 'hang around', 'hang on', 'hang out', 'hang up', 'have on', 'head back', 'head for', 'head toward', 'hear about', 'hear of', 'heat up', 'help out', 'hit on', 'hold against', 'hold off', 'hold on', 'hold out', 'hold up', 'hook up', 'hurry up', 'keep at', 'keep away', 'keep down', 'keep from', 'keep off', 'keep on', 'keep to', 'keep up', 'kick back', 'kick out', 'knock off', 'knock out', 'knock over', 'know about', 'lay down', 'lay off', 'lead up', 'leave behind', 'leave off', 'leave out', 'leave over', 'let down', 'let in', 'let off', 'let on', 'let out', 'let up', 'lie around', 'lift up', 'light up', 'lighten up', 'line up', 'live with', 'lock in', 'lock out', 'lock up', 'look around', 'look at', 'look down', 'look forward', 'look into', 'look out', 'look over', 'look up', 'look up', 'luck out', 'make for', 'make of', 'make up', 'mess up', 'mix up', 'monkey around', 'move in', 'move out', 'narrow down', 'pay back', 'pay for', 'pay off', 'pay up', 'pick on', 'pick out', 'pick up', 'pile up', 'piss off', 'plan ahead', 'plan for', 'plan on', 'plug in', 'plug in/into', 'plug up', 'point out','points out','point to', 'print out', 'pull off', 'pull up', 'put back', 'put down', 'put in', 'put off', 'put out', 'put past', 'put to', 'put together', 'put up', 'put up', 'put up', 'ring up', 'rip off', 'rip up', 'rule out', 'run across', 'run around', 'run down', 
'run into', 'run out', 'run over', 'run up', 'screw on', 'screw out', 'screw up', 'see about', 'sell out', 'set up', 'settle down', 'settle for', 'shake up', 'show off','shun away', 'shut off', 'shut up', 'sign in', 'sign out', 'sit down', 'slow down', 'sneak in/into', 'sneak out', 'sort out', 'space out', 'speed up','stand around', 'stand for', 'stand up', 'start off', 'start out', 'start up', 'stay off', 'stay out', 'stay up', 'step on', 'stick around', 'stick out', 'stick to', 'stick up', 'stick with', 'stop off', 'stop over', 'straighten out', 'stress out', 'switch off', 'switch on', 'take part', 'take back', 'take in', 'take out', 'take out', 'take up', 'talk down', 'talk into', 'talk out', 'talk to', 'tear down', 'tear off', 'tell apart', 'tell on', 'think about', 'think ahead', 'think up', 'throw away', 'throw out', 'throw up', 'track down', 'trade in', 'trick into', 'try on', 'try out', 'turn around', 'turn down', 'turn in', 'turn into', 'turn off', 'turn on', 'turn out', 'turn over', 'turn up', 'use up', 'wake up', 'wash off', 'wash up', 'watch out', 'wear down', 'wear off', 'wear out', 'wind up', 'wipe off', 'wipe out', 'wipe up', 'work in', 'work out', 'work up', 'wrap up', 'zip up']

var arrayLength=phrasalVerbs.length

for (var i=0; i<arrayLength;i++) {
    var thirdForm = phrasalVerbs[i].split(' ')[0]+'s '+phrasalVerbs[i].split(' ')[1];
    phrasalVerbs.push(thirdForm);
}
export default phrasalVerbs;