let replace = [
    { 'absence of': 'no or none' },
    { 'abundance': 'enough or plenty' },
    { 'accede to': 'agree' }, { 'accedes to': 'agrees' }, { 'acceded to': 'agreed' }, { 'acceding to': 'agreeing' },
    { 'advantageous': 'helpful' },
    { 'ameliorates': 'improves' }, { 'ameliorated': 'improved' }, { 'ameliorating': 'improving' },{ 'ameliorate': 'improve' }, 
    { 'cognizant': 'aware' },
    { 'commensurate': 'equal' },
    { 'consolidates': 'combines' }, { 'consolidated': 'combined' }, { 'consolidating': 'combining' },{ 'consolidate': 'combine' }, 
    { 'deleterious': 'harmful' },
    { 'disseminates': 'issue or send' }, { 'disseminated': 'issue or send' }, { 'disseminating': 'issue or send' },{ 'disseminate': 'issue or send' }, 
    { 'endeavors': 'efforts' },
    { 'erroneous': 'wrong' },
    { 'expeditious': 'fast' },
    { 'inception': 'start' },
    { 'leverages': 'uses' }, { 'leveraged': 'used' }, { 'leveraging': 'using' },{ 'leverage': 'use' }, 
    { 'proficiency': 'skill' }, { 'proficiencies': 'skills' },
    { 'promulgates': 'issues or publishes' }, { 'promulgated': 'issued or published' }, { 'promulgating': 'issuing or publishing' },{ 'promulgate': 'issue or publish' }, 
    { 'proximity': 'near' },
    { 'subsequently': 'after or later' },
    { 'utilizes': 'uses' }, { 'utilized': 'used' }, { 'utilizing': 'using' }, { 'utilize': 'use' }, 
    { 'absence of': 'no, none' },
    { 'abundance': 'enough, plenty, a lot' },
    { 'accentuate': 'stress' },
    { 'accommodation': 'home' },
    { 'accompanying': 'with' },
    { 'accomplish': 'finish' }, 
    { 'according to records': 'records show' },
    { 'according to studies': 'studies proves that' },
    { 'accordingly': 'in line with this, so' },
    { 'acquiesce': 'agree' },
    { 'acquires': 'obtains, receives' },{ 'acquired': 'obtained, received' },{ 'acquiring': 'obtaining, receiving'},{'acquire':'obtain, receive' },
    { 'additional': 'extra, more' },
    { 'adjacent': 'next to' },
    { 'adjustment': 'change, alteration' },
    { 'admissible': 'allowed, acceptable' },
    { 'advantageous': 'useful, helpful' },
    { 'affix': 'add, write, fasten, stick on, fix to' },
    { 'afford an opportunity': 'let, allow' },
    { 'aforesaid': 'this, earlier in this document' },
    { 'aggregate': 'total' },
    { 'aligned': 'lined up, in line' },
    { 'alleviate': 'ease, reduce' },
    { 'allocate': 'divide, share, give' },
    { 'along the lines of': 'like, as in' },
    { 'alternative': '(a) choice, (the) other' },
    { 'alternatively': 'or, on the other hand' },
    { 'amendment': 'change' },
    { 'among others':'avoid ending a list with "among others" as it is considered vagueness and not recommended in academic writing"'},
    { 'among other':'avoid ending a list with "among other" as it is considered vagueness and not recommended in academic writing"'},
    { 'anticipates': 'expects' },{ 'anticipated': 'expected' },{ 'anticipating': 'expecting' },{ 'anticipate': 'expect' },
    { 'apparent': 'clear, plain, obvious' },
    { 'application': 'use' },
    { 'appreciable': 'large, great' },
    { 'apprise': 'inform, tell' },
    { 'appropriate': 'proper, right, suitable' },
    { 'appropriate to': 'suitable for' },
    { 'approximately': 'roughly' },
    { 'as a consequence of': 'because' },
    { 'as of the date of': 'from' },
    { 'as regards': 'on the subject of' },
    { 'ascertain': 'establish' },
    { 'assemble': 'build, gather' },
    { 'assistance': 'help' },
    { 'at an early date': 'soon (or say when)' },
    { 'at its discretion': 'can, may' },
    { 'at the moment': 'now, when' },
    { 'at the present time': 'now' },
    { 'attributable to': 'because of' },
    { 'authorize': 'allow, let' },
    { 'authority': "right, power"},
    { 'axiomatic': 'obvious' },
    { 'belated': 'late' },
    { 'beneficial': 'helpful, useful' },
    { 'bestow': 'give, award' },
    { 'breaches': 'breaks' },{ 'breached': 'broke' },{ 'breaching': 'breaking' },{ 'breach': 'break' },
    { 'by means of': 'by' },
    { 'calculate': 'decide' },
    { 'ceases': 'finishes, stops, ends' },{ 'ceased': 'finished, stopped, ended' },{ 'ceasing': 'finishing, stopping, ending' },{ 'cease': 'finish, stop, end' },
    { 'circumvent': 'avoid, skirt, circle' },
    { 'clarification': 'explanation, help' },
    { 'combines': 'mixes' },{ 'combined': 'mixed' },{ 'combining': 'mixing' },{ 'combine': 'mix' },
    { 'combined': 'together' },
    { 'commences': 'starts, begins' },{ 'commenced': 'started, began' },{ 'commencing': 'starting, beginning' },{ 'commence': 'start, begin' },
    { 'communicate': 'talk, write, telephone (be specific)'},
    { 'compile': 'collect' },
    { 'complete': 'finish' },
    { 'completion': 'end' },
    { 'complies with': 'meets' },{ 'complied with': 'met' },{ 'complying with': 'meeting' },{ 'comply with': 'meet' },
    { 'component': 'part' },
    { 'comprises': 'includes' },
    { 'conceal': 'hide' },
    { 'concur': 'agree' },
    { 'constitutes': 'forms, is' },
    { 'construe': 'interpret' },
    { 'consult': 'talk to, meet, ask' },
    { 'contemplate': 'think' },
    { 'contrary to': 'against, despite' },
    { 'costs the sum of': 'costs' },
    { 'courteous': 'polite' },
    { 'cumulative': 'added together' },
    { 'currently': 'now (or edit out)' },
    { 'customary': 'usual, normal' },
    { 'deem to be': 'treat as' },
    { 'defer': 'put off, delay' },
    { 'deficiency': 'lack of' },
    { 'delete': 'cross out' }, 
    { 'demonstrate': 'show, prove' },
    { 'denote': 'show' },
    { 'depict': 'show' },
    { 'designate': 'point out, show, name' }, 
    { 'desire': 'wish, want' },
    { 'despite the fact that': 'though, although' }, 
    { 'determine': 'decide, work out, set, end' }, 
    { 'detrimental': 'harmful, damaging' }, 
    { 'difficulties': 'problems' }, 
    { 'diminish': 'lessen, reduce' }, 
    { 'disburse': 'pay, pay out' }, 
    { 'discontinue': 'stop, end' },
    { 'discrete': 'separate' }, 
    { 'disseminate': 'spread' }, 
    { 'documentation': 'papers, documents' }, 
    { 'domiciled in': 'living in' }, 
    { 'due to the fact that': 'because, as' },
    { 'Due to': 'Because of'},
    { 'due to': 'because of'},
    { 'during which time': 'while' }, 
    { 'dwelling': 'home' }, 
    { 'eligible': 'allowed, qualified' }, 
    { 'elucidate': 'explain, clarify' }, 
    { 'empower': 'allow, let' },
    { 'enables': 'allows' },{ 'enabled': 'allowed' },{ 'enabling': 'allowing' },{ 'enable': 'allow' },
    { 'enclosed': 'inside, with' }, 
    { 'encounter': 'meet' }, 
    { 'enquire': 'ask' }, 
    { 'enquiry': 'question' }, 
    { 'entitlement': 'right' }, 
    { 'envisage': 'expect, imagine' }, 
    { 'equivalent': 'equal, the same' }, 
    { 'evaluates': 'tests, checks' }, { 'evaluated': 'tested, checked' }, { 'evaluating': 'testing, checking' }, { 'evaluate': 'test, check' }, 
    { 'evince': 'prove' }, 
    { 'ex officio': 'because of his or her position' }, 
    { 'excluding': 'apart from, except' }, 
    { 'exclusively': 'only' }, 
    { 'exempt from': 'free from' }, 
    { 'expedite': 'accelerate' }, 
    { 'expeditiously': 'as soon as possible, quickly' }, 
    { 'expenditure': 'spending' }, 
    { 'extremity': 'limit' },
    { 'finalizes': 'ends, finishes' }, 
    { 'finalized': 'ended, finished' }, 
    { 'finalizing': 'ending, finishing' }, 
    { 'finalize': 'end, finish' }, 
    { 'for the duration of': 'during, while' }, 
    { 'for the purpose of': 'to, for' }, 
    { 'for the reason that': 'because' },
    { 'formulate': 'plan, devise' }, 
    { 'forthwith': 'now, at once' }, 
    { 'frequently': 'often' }, 
    { 'furnish': 'give' }, 
    { 'further to': 'after, following' },
    { 'generate': 'produce' }, 
    { 'give consideration to': 'consider' }, 
    { 'henceforth': 'from now on, from today' }, 
    { 'hereby': 'now, by this (or edit out)' }, 
    { 'herein': 'here (or edit out)' }, 
    { 'hereinafter': 'after this (or edit out)' }, 
    { 'hereof': 'of this' },
    { 'hereto': 'to this' }, 
    { 'heretofore': 'until now, previously' }, 
    { 'hereunder': 'below' }, 
    { 'herewith': 'with this (or edit out)' }, 
    { 'hitherto': 'until now' }, 
    { 'hold in abeyance': 'wait, postpone' }, 
    { 'hope and trust': 'hope, trust (but not both)' }, 
    { 'if when': 'if, when (but not both)' }, 
    { 'immediately': 'at once, now' }, 
    { 'imply': 'suggest, hint at' },
    { 'important': 'Use a stronger adjective, such as "significant" or "crucial"'},
    { 'in accordance with': 'as under, in line with, because of' },
    { 'in addition to': 'and, as well as' }, 
    { 'in advance': 'before' }, 
    { 'in case of': 'if' }, 
    { 'in conjunction with': 'and, with' }, 
    { 'in connection with': 'for' }, 
    { 'in consequence': 'because, as a result' }, 
    { 'in excess of': 'more than' }, 
    { 'in lieu of': 'instead of' }, 
    { 'in order that': 'so that' }, 
    { 'In order to':'To'},
    { 'in order to':'to'},
    { 'in receipt of': 'get, have, receive' }, 
    { 'in the absence of': 'without' }, 
    { 'in the course of': 'while, during' }, 
    { 'in the event of/that': 'if' }, 
    { 'in the majority of instances': 'most, mostly' },
    { 'majority of':'most'},
    { 'in the near future': 'soon' }, 
    { 'in the neighborhood of': 'around' }, 
    { 'in view of the fact that': 'as, because' }, 
    { 'inappropriate': 'wrong, unsuitable' }, 
    { 'inception': 'start, beginning' }, 
    { 'incorporating': 'that includes' }, 
    { 'incur': 'have to pay, owe' }, 
    { 'indicates': 'shows, suggests' }, { 'indicated': 'showed, suggested' }, { 'indicating': 'showing, suggesting' },{ 'indicate': 'show, suggest' },  
    { 'initially': 'at first' }, 
    { 'initiate': 'begin, start' }, 
    { 'insert': 'put in' }, 
    { 'instances': 'cases' }, 
    { 'intend to': 'will' }, 
    { 'irrespective of': 'despite, even if' }, 
    { 'jeopardize': 'risk, threaten' }, 
    { 'large number of': 'many, most (or say how many)' },
    { 'like':'such as'}, 
    { 'locality': 'place, area' }, 
    { 'locate': 'find, put' }, 
    { 'magnitude': 'size' }, 
    { 'marginal': 'small, slight' }, 
    { 'materialize': 'happen, occur' }, 
    { 'material': 'relevant' }, 
    { 'may in the future': 'may, might, could' }, 
    { 'mislay': 'lose' }, 
    { 'nevertheless': 'but, however, even so' }, 
    { 'notwithstanding': 'even if, despite, still, yet' },
    { 'occasioned by': 'caused by, because of' }, 
    { 'on behalf of': 'for' }, 
    { 'on numerous occasions': 'often' }, 
    { 'on the grounds that': 'because' }, 
    { 'on the occasion that': 'when, if' }, 
    { 'operate': 'work, run' }, 
    { 'optimum': 'best, ideal' }, 
    { 'option': 'choice' }, 
    { 'ordinarily': 'normally, usually' }, 
    { 'owing to': 'because of' }, 
    { 'partially': 'partly' }, 
    { 'particulars': 'details, facts' }, 
    { 'per annum': 'a year' }, 
    { 'permissible': 'allowed' }, 
    { 'permit': 'let, allow' }, 
    { 'personnel': 'people, staff' }, 
    { 'persons': 'people' },
    { 'peruse': 'read, read carefully' }, 
    { 'possess': 'have, own' }, 
    { 'possessions': 'belongings' }, 
    { 'practically': 'almost, nearly' }, 
    { 'predominant': 'main' }, 
    { 'prescribe': 'set, fix' }, 
    { 'preserve': 'keep, protect' }, 
    { 'principal': 'main' }, { 'prior to': 'before' }, 
    { 'procure': 'obtain, arrange' }, 
    { 'profusion of': 'plenty, too many (or say how many)' },
    { 'prohibits': 'bans, stops' },{ 'prohibited': 'banned, stopped' },{ 'prohibiting': 'banning, stopping' },{ 'prohibit': 'ban, stop' }, 
    { 'projected': 'estimated' }, 
    { 'prolonged': 'long' }, 
    { 'promptly': 'quickly, at once' }, 
    { 'promulgate': 'advertise, announce' }, 
    { 'proportion': 'part' }, 
    { 'provided that': 'if, as long as' }, 
    { 'provisions': 'rules, terms' },
    { 'proximity': 'closeness, nearness' }, 
    { 'pursuant to': 'under, because of, in line with' }, 
    { 'referred to as': 'called' },
    { 'refers to': 'mentions' }, 
    { 'reimburse': 'repay, pay back' }, 
    { 'reiterate': 'repeat, restate' }, 
    { 'remainder': 'the rest, what is left' }, 
    { 'remittance': 'payment' }, 
    { 'remuneration': 'pay, wages, salary' }, 
    { 'represents': 'shows, stands for, is' }, 
    { 'request': 'ask, question' }, 
    { 'requirements': 'needs, rules' }, 
    { 'restriction': 'limit' }, 
    { 'scrutinise': 'read (look at) carefully' }, 
    { 'select': 'choose' }, 
    { 'settle': 'pay' }, 
    { 'similarly': 'also, in the same way' }, 
    { 'solely': 'only' },
    { 'specified': 'given, written, set' },  
    { 'statutory': 'legal, by law' }, 
    { 'subject to': 'depending on, under, keeping to' }, 
    { 'submit': 'send, give' },
    { 'subsequently': 'later' }, 
    { 'substantially': 'more or less' }, 
    { 'supplementary': 'extra, more' }, 
    { 'terminate': 'stop, end' }, 
    { 'that being the case': 'if so' },
    { 'the question as to whether': 'whether' }, 
    { 'thereafter': 'then, afterwards' }, 
    { 'thereby': 'by that, because of that' }, 
    { 'therein': 'in that, there' }, 
    { 'thereof': 'of that' }, 
    { 'thereto': 'to that' },
    { 'to date': 'so far, up to now' }, 
    { 'to the extent that': 'if, when' }, 
    { 'transfer': 'change, move' },
    { 'transmit': 'send' }, 
    { 'ultimately': 'in the end, finally' }, 
    { 'unavailability': 'lack of' }, 
    { 'undertake': 'agree, promise, do' }, 
    { 'uniform': 'same, similar' }, 
    { 'unilateral': 'one-sided, one-way' }, 
    { 'unoccupied': 'empty' }, 
    { 'until such time': 'until' }, 
    { 'variation': 'change' }, 
    { 'virtually': 'edit out' }, 
    { 'visualize': 'see, predict' }, 
    { 'ways and means': 'ways' },
    { 'whatsoever': 'whatever, what, any' },
    { 'whensoever': 'when' }, 
    { 'whereas': 'but' }, 
    { 'whether or not': 'whether' }, 
    { 'with a view to': 'to, so that' }, 
    { 'with effect from': 'from' }, 
    { 'with reference to': 'regarding' }, 
    { 'with regard to': 'regarding' }, 
    { 'with the minimum of delay': 'quickly (or say when)' },
]

export default replace;