let transitions = [
    "Nevertheless",
    "However",
    "Nonetheless",
    "Consequently",
    "Undoubtedly",
    "Furthermore",
    "In addition to this",
    "To begin with",
    "Subsequently",
    "Besides",
    "Similarly",
    "Likewise",
    "In the same manner",
    "Indeed",
    "Notably",
    "Particularly",
    "In fact",
    "Specifically",
    "Namely",
    "Accordingly",
    "As a consequence",
    "Therefore",
    "Thus",
    "Hence",
    "As a result",
    "Often",
    "On the other hand",
    "For example",
    "For instance",
    "Firstly",
    "Secondly",
    "Moreover",
    "As a matter of fact",
    "In like manner",
    "Equally important",
    "By the same token",
    "Of course",
    "In reality",
    "After all",
    "In this case",
    "By all means",
    "That is to say",
    "On the positive side",
    "With this in mind",
    "Surprisingly",
    "In particular",
    "Obviously",
    "Ultimately",
    "Definitely",
    "In summary",
    "In any event",
    "On the whole",
    "By and large",
    "In either case",
    "All in all",
    "Ordinarily",
    "In short",
    "In essence",
    "In brief",
    "Altogether",
    "As shown above",
    "For the most part",
    "Finally",
    "Consequently",
    "Occasionally",
    "Presently",
    "Instantly",
    "Sooner or later",
    "All of a sudden",
    "Henceforth",
    "Further",
    "Generally speaking",
    "All things considered",
    "Given these points",
    "As has been noted",
    "In a word",
    "In the long run",
    "In that case",
    "For this reason",
    "Under those circumstances",
    "Accordingly",
    "Thereupon",
    "Forthwith",
]



export default transitions;