let vague = [
    "acknowledge",
    "acknowledges",
    "acknowledged",
    "appreciate",
    "appreciates",
    "appreciated",
    "it appears that",
    "be aware of",
    "be familiar with",
    "be informed of",
    "comprehend",
    "comprehends",
    "comprehended",
    "create",
    'something',
    "somebody",
    "someone",
    "somewhat",
    'somewhere',
    'somehow',
    "Some",
    'some',
    "creates",
    "created",
    "feel",
    "feels",
    "felt",
    'makes','made','making','make',
    "know",
    "knows",
    "known",
    "big",
    "bigger",
    "make",
    "makes",
    "made",
    "undergo",
    "undertake",
    "understands",
    "undertakes",
    "understood",
    "undertook",
 ]



 export default vague;

 