let vague = [
    "acknowledge",
    "acknowledges",
    "acknowledged",
    "appreciate",
    "appreciates",
    "appreciated",
    "it appears that",
    "be aware of",
    "be familiar with",
    "be informed of",
    "comprehend",
    "comprehends",
    "comprehended",
    "create",
    "creates",
    "created",
    "describe",
    "describes",
    "described",
    "experience",
    "experiences",
    "experienced",
    "feel",
    "feels",
    "felt",
    "generate",
    "generates",
    "generated",
    "illustrate",
    "illustrates",
    "illustrated",
    "know",
    "knows",
    "known",
    "make",
    "makes",
    "made",
    "participate in",
    "rely",
    "recognize",
    "undergo",
    "understand",
    "undertake",
    "understands",
    "undertakes",
    "understood",
    "undertook",
 ]
 vague = vague.sort();


 export default vague;

 