const weasel = [
    "as being",
    "as to weather",
    "at all times",
    "at the end of the day",
    "at the present time",
    'always',
    "never",
    "in all cases",
    "in many cases",
    "in most cases",
    "in some cases",
    'literally',
    'essentially',
    'virtually',
    'usually',
    'basically',
    'simply',
    'something',
    "somebody",
    "probably",
    'possibly',
    'perhaps',
    'totally',
    "absolutely",
    "anything",
    "almost",
    "etc.",
    'maybe',
    'often',
    '(?<=a )leading',
    'cutting-edge',
    'that being said',
    'could be',
    "someone",
    "somewhat",
    'somewhere',
    'somehow',
    'someday',
    'everyday',
    'a growing body of evidence',                       
    'it is commonly known',
    'as everyone knows',
    'as everybody knows',
    'experience proves',
    'experience indicates',
    'people say',
    'it stands to reason',
    'some say',
    'some argue',
    'it is known that',
    'it is commonly known that',
    'anybody',
    'anyone',
    'everybody',
    'everyone',
    '(?:in|of|to|from|on) (the )?(\\w+\\s)?society'   
]
export default weasel