let wordiness = [
    "allegedly",
    "as a matter of fact",
    "by means of",
    "current trend that",
    "despite the fact that",
    "for this reason",
    "it is noted that",
    "it is evident that",
    "it can be said that",
    "it can be concluded that",
    "it may be said that",
    "it has been found out",
    "it has long been known that",
    "it is a fact that",
    'it is a clear indication that',
    "It is arguable that",
    "It is unarguable that",
    "it is worth mentioning that",
    "it is worth noting that",
    "it is argued that",
    "it had been argued that",
    "it is necessary to state that",
    "it is imperative to",
    "it is important to note that",
    "it has long been known that",
    "it is a fact that",
    "it has been found that",
    "it is well known that",
    "it may be said that",
    "it should be noted that",
    "it was evident that",
    "it has been identified that",
    "that said",
    "a sufficient amount of",
    "along the lins of",
    "at the present time",
    "at this point in time",
    "despite the fact that",
    "due to the fact the fact that",
    "during the time that",
    "for the reason that",
    "five consideration to",
    "happens to be",
    "has been proved to be",
    "imperative to note that",
    "in close proximity to",
    "in all cases",
    "in many cases",
    "in most cases",
    "in order to",
    "in some cases",
    "in conclusion",
    "In the conclusion",
    "in the event that",
    "in the near future",
    "in the vicinity of",
    "in summary",
    "is in a position to",
    "it is interesting to note that",
    "in a position to",
    "manner in which",
    "might be able to",
    "not with standing the fact that",
    "on the basis of",
    "prior to",
    "provided that",
    "reach a conclusion",
    "serves a function of being",
    "the question as to",
    "the reason is because",
    "to conclude",
    "to sum up",
    "to summarize",
    "utilize",
    "utilization",
    "with reference to",
    "with the exception that"
  ]

var arrayLength = wordiness.length

  for (var i=0; i<arrayLength;i++) {
      var capital = wordiness[i][0].toUpperCase()+wordiness[i].slice(1,wordiness[i].length)
      wordiness.push(capital);
  }

export default wordiness;